# Generated by Django 5.0.6 on 2024-12-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cartitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
